name: tests

on:
  push:
  pull_request:

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        testbench: [^4.0, ^5.0, ^6.0]
        exclude:
          - php: 7.2
            testbench: ^6.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ./vendor
          key: dependencies-testbench-${{ matrix.testbench }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: none
      - name: Install testbench
        run: composer require "orchestra/testbench=${{ matrix.testbench }}" --dev --no-update
      - name: Install Composer dependencies
        run: composer install --no-progress --optimize-autoloader
      - name: Test with phpunit
        run: vendor/bin/phpunit
